# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kevin egbert
email: hey@kevinegbert.com
description: > # this means to ignore newlines until "baseurl:
# baseurl: "/kae" # the subpath of your site, e.g. /blog
url: "http://kevinegbert.com" # the base hostname & protocol for your site
# twitter_username: kaegbert
github_username:  kaegbert
permalink: /:title

# Build settings
markdown: kramdown
port: 4000
